const HERITAGE_FACTS = [
  'The sari is usually made from one unstitched length of cloth, styled through drape rather than tailoring.',
  'Japanese kimono are cut from straight panels, which helps preserve the textile pattern.',
  'Indigo dye has been used in textile traditions across West Africa, India, Japan, and the Americas.',
  'Ikat patterns are dyed into yarn before weaving, so the motif is built into the cloth.',
  'Batik uses wax resist to protect parts of fabric before dye is applied.',
  'Harris Tweed must be handwoven in the Outer Hebrides to carry the protected name.',
  'The qipao became a modern fitted dress in Shanghai during the early twentieth century.',
  'A lehenga is a skirt-based ensemble often paired with a choli and dupatta.',
  'Moroccan kaftans are known for rich trims, embroidery, and flowing structure.',
  'The hanbok silhouette often uses a short jacket with a full, high-waisted skirt or trousers.',
  'A dashiki usually features a loose fit and decorative neckline rooted in West African dress.',
  'The Scottish kilt is traditionally made from tartan, a woven pattern associated with clans and regions.',
  'A poncho is shaped from a simple cloth opening, making it one of fashion’s oldest practical forms.',
  'Espadrilles traditionally use rope soles, often made with jute.',
  'The guayabera shirt is known for pleats and pockets, especially in Caribbean and Latin American dress.',
  'The Nehru jacket takes its name from Jawaharlal Nehru and is defined by a close standing collar.',
  'Cowrie shells have appeared in clothing and adornment across Africa, Asia, and Oceania.',
  'Phulkari embroidery from Punjab often uses bright floss thread on shawls and dupattas.',
  'Kantha stitching from Bengal turns running stitches into texture, repair, and storytelling.',
  'Kente cloth from Ghana is woven in strips with colors and patterns that carry social meaning.',
  'A huipil is a traditional tunic worn in many Indigenous communities in Mexico and Central America.',
  'A rebozo can work as a shawl, scarf, baby carrier, and ceremonial textile.',
  'The cheongsam and qipao are related names for a close-fitting Chinese dress form.',
  'Andean aguayo cloth is often used for carrying goods and children as well as for dress.',
  'Mud cloth, or bogolanfini, uses fermented mud and plant dyes to create graphic patterns.',
  'A boubou is a flowing robe worn across parts of West Africa.',
  'The barong tagalog is a formal embroidered shirt from the Philippines.',
  'Tapa cloth is made from bark fibers in several Pacific Island traditions.',
  'The Vietnamese ao dai pairs a long tunic with trousers for a graceful vertical line.',
  'The agbada is a wide-sleeved robe ensemble worn for important occasions in West Africa.',
  'Bandhani tie-dye from India creates dotted patterns by tying tiny points of fabric before dyeing.',
  'Shibori is a Japanese resist-dye family that includes folding, stitching, binding, and clamping.',
  'Mola panels from Panama use reverse applique to build layered, colorful designs.',
  'The Mexican serape is known for stripes and blanket-like warmth.',
  'Paisley motifs grew from boteh forms associated with Persian and South Asian textile design.',
  'The mandarin collar is a short unfolded standing collar seen across many jacket traditions.',
  'A dupatta can change a whole outfit by shifting drape, color balance, and movement.',
  'Zari uses metallic threads to add shimmer to South Asian textiles.',
  'Chikankari embroidery from Lucknow is prized for delicate whitework and shadow effects.',
  'Kalamkari textiles are traditionally drawn or block-printed with natural dyes.',
  'Patola saris are double-ikat textiles where warp and weft are both resist-dyed before weaving.',
  'Ajrakh block printing is known for geometric repeats and deep indigo and madder tones.',
  'Jamdani weaving creates motifs directly on the loom with supplementary weft.',
  'Banarasi brocade is famous for silk, metallic thread, and ornate woven motifs.',
  'The sherwani is a formal long coat often worn for weddings and ceremonial dress.',
  'The kurta is a versatile tunic worn across South Asia in casual and formal settings.',
  'The turban can signal region, faith, ceremony, rank, or personal style depending on context.',
  'The fez is a brimless felt hat with roots in Ottoman-era dress.',
  'The beret became associated with French style but has older regional and military histories.',
  'The trench coat evolved from practical military outerwear into a city wardrobe staple.',
  'Jeans began as durable workwear before becoming a global everyday uniform.',
  'The T-shirt moved from undergarment to outerwear during the twentieth century.',
  'Sneakers became fashion objects when sport, music, and streetwear cultures converged.',
  'The little black dress became a modern fashion idea because it was simple, adaptable, and repeatable.',
  'Bias cutting lets woven fabric skim the body by placing the grain diagonally.',
  'Pleats add volume while allowing fabric to collapse flat when the body is still.',
  'A dart shapes flat fabric around curves without adding a separate piece.',
  'A gusset adds range of motion, often under arms or at crotch seams.',
  'A godet is a triangular insert that adds flare to a skirt or sleeve.',
  'Raglan sleeves extend to the neckline, removing the traditional shoulder seam.',
  'Dolman sleeves are cut wide at the armhole and narrow toward the wrist.',
  'Princess seams shape garments through long curved lines instead of waist darts.',
  'A yoke is a shaped panel that supports or decorates a garment.',
  'Selvedge is the finished edge of woven fabric, often valued in denim.',
  'Raw denim is denim that has not been washed after dyeing and weaving.',
  'Twill weave creates diagonal ribs and is common in denim, chinos, and suiting.',
  'Satin weave creates a smooth face by floating yarns over several threads.',
  'Organza is crisp and sheer, while chiffon is soft and flowing.',
  'Velvet has a pile surface, which gives it depth and directional shine.',
  'Crepe fabric has a pebbled texture from tightly twisted yarns or finishing.',
  'Taffeta is crisp, smooth, and often used when designers want structure and rustle.',
  'Linen wrinkles easily because flax fibers have low elasticity.',
  'Wool can insulate even when damp because of its fiber structure.',
  'Silk is naturally strong for its fineness and takes dye beautifully.',
  'Cotton breathes well and became global through both agriculture and industrial weaving.',
  'Rayon was developed as an early manufactured fiber with a silk-like drape.',
  'Nylon popularized synthetic stockings before becoming a major performance textile.',
  'Polyester became dominant because it is durable, stable, and easy to care for.',
  'Elastane changed fit by adding stretch recovery to woven and knitted garments.',
  'A capsule wardrobe uses fewer pieces designed to combine in many ways.',
  'Tailoring often begins with balance: where shoulder, waist, and hem lines sit on the body.',
  'The lapel roll is one of the subtle signs of quality in a tailored jacket.',
  'Canvas inside a suit jacket helps it mold to the wearer over time.',
  'French seams enclose raw edges for a clean inside finish.',
  'Flat-felled seams are strong and common in jeans and shirts.',
  'Hong Kong binding finishes seams with bias strips for a polished interior.',
  'A blind hem hides most stitches on the outside of a garment.',
  'Topstitching can strengthen a seam and become a visible design line.',
  'Couture fittings often refine millimeters, not inches.',
  'A toile or muslin is a test garment used before cutting final fabric.',
  'Pattern grading changes a pattern across sizes while keeping design proportions.',
  'Ease is the extra room that lets a garment move beyond exact body measurements.',
  'Negative ease means a garment is smaller than the body and relies on stretch.',
  'A block pattern is a base shape used to create many garment designs.',
  'The armscye is the armhole curve, one of the hardest fit points to perfect.',
  'The rise of trousers shapes comfort as much as visual proportion.',
  'Hem length can change the perceived balance of the entire outfit.',
  'Monochrome dressing can make texture and silhouette more visible.',
  'Complementary colors sit opposite each other on the color wheel and create high contrast.',
  'Analogous colors sit near each other and usually feel calmer in an outfit.',
  'A single accessory can shift an outfit from casual to formal by changing context.',
  'Black absorbs visual detail, so silhouette becomes especially important.',
  'White garments show construction, shadow, and fit very clearly.',
  'Metal hardware can make a soft garment feel sharper and more structured.',
  'Matte textures usually read quieter than shiny textures under the same lighting.',
  'A high waist can visually lengthen the leg line.',
  'Dropped shoulders soften a silhouette and often create a relaxed mood.',
  'Sharp shoulders can make a jacket feel formal, powerful, or architectural.',
  'A-line skirts widen from waist to hem, creating movement without clinging.',
  'Column silhouettes emphasize vertical continuity.',
  'Layering works best when each layer has a distinct weight, edge, or purpose.',
  'A well-placed belt can change proportion more than color can.',
  'Shoe shape affects the mood of an outfit as much as heel height.',
  'Bags can anchor scale: small bags feel delicate, large totes feel practical.',
  'Fashion illustration often exaggerates proportions to communicate mood quickly.',
  'Runway styling is often more theatrical than retail styling because it must read from far away.',
  'Editorial fashion images use pose, light, and styling to create a point of view.',
  'Street style became influential because real outfits can reveal how trends are actually worn.',
  'Vintage clothing preserves past construction choices that modern production may skip.',
  'Upcycling changes an existing garment into a new design instead of starting with raw cloth.',
  'Visible mending turns repair into decoration and memory.',
  'Deadstock fabric is unused existing fabric that can be redirected into new garments.',
];

const GLOBAL_STYLE_NOTES = [
  'A clean product photo helps virtual try-on models preserve garment color.',
  'Full-body photos usually give better hem and shoe context than close crops.',
  'Soft daylight often gives AI editors fewer harsh shadows to reconcile.',
  'Flat lays are useful for showing garment shape, but model photos reveal drape.',
  'Busy backgrounds can distract image models from the clothing boundary.',
  'Logos need sharp references because small text is easy for generators to distort.',
  'Sleeves are one of the hardest regions because hands, folds, and cuffs overlap.',
  'Necklines are fit-sensitive because hair, jewelry, collarbones, and shadows meet there.',
  'Transparent and sheer fabrics are difficult because they require body-aware layering.',
  'Print alignment is a strong test of whether a try-on preserved garment identity.',
  'Drape depends on fabric weight, not only on garment outline.',
  'A garment can look expensive when fit, pressing, and proportion are quiet.',
  'Fashion images feel more believable when shadows match the original photo.',
  'Texture tells the eye whether fabric is cotton, silk, denim, knit, or leather.',
  'Wrinkles are not always flaws; they can make fabric feel real.',
  'A collar can define the attitude of a shirt before color does.',
  'Cuffs are small, but they often reveal tailoring quality.',
  'The best styling usually has one clear focal point.',
  'Repeating one color in two places can make an outfit feel intentional.',
  'Contrast can come from shape, shine, weight, texture, or color.',
  'A relaxed fit still needs proportion; oversized does not mean shapeless.',
  'Minimal outfits depend heavily on fabric quality and line.',
  'Maximal outfits work when one rhythm ties the pieces together.',
  'Accessories can add scale references that help a look feel grounded.',
];

const REGIONS = [
  'India',
  'Japan',
  'Ghana',
  'Mexico',
  'Morocco',
  'Korea',
  'Vietnam',
  'Scotland',
  'Peru',
  'Indonesia',
  'Nigeria',
  'France',
  'Italy',
  'Turkey',
  'the Philippines',
  'Panama',
];

const CRAFTS = [
  'weaving',
  'embroidery',
  'dyeing',
  'pleating',
  'tailoring',
  'beadwork',
  'block printing',
  'applique',
  'knitting',
  'leatherwork',
];

const MATERIALS = [
  'silk',
  'cotton',
  'linen',
  'wool',
  'denim',
  'velvet',
  'organza',
  'chiffon',
  'brocade',
  'tweed',
];

const generatedFacts = [
  ...REGIONS.flatMap((region) => CRAFTS.map((craft) => (
    `${region} has fashion traditions where ${craft} can carry identity, ceremony, climate, and everyday practicality.`
  ))),
  ...MATERIALS.flatMap((material) => [
    `${material[0].toUpperCase()}${material.slice(1)} changes how a silhouette behaves because fiber, weave, and finish affect drape.`,
    `In a try-on image, ${material} needs believable highlights and shadows to read like real fabric.`,
    `Stylists often balance ${material} with a contrasting texture so the outfit does not feel flat.`,
  ]),
];

export const FASHION_FACTS = [
  ...HERITAGE_FACTS,
  ...GLOBAL_STYLE_NOTES,
  ...generatedFacts,
].slice(0, 320);
